AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World Lambda Function

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 30
      MemorySize: 256
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: 
                - !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:inference-profile/us.amazon.nova-2-lite-v1:0'
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /quote
            Method: get
        HelloWorldApiPost:
          Type: Api
          Properties:
            Path: /quote
            Method: post
        HelloWorldApiOptions:
          Type: Api
          Properties:
            Path: /quote
            Method: options

Outputs:
  DailyQuoteApi:
    Description: "API Gateway endpoint URL for Daily Quote function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/quote/"
  HelloWorldFunction:
    Description: "Daily Quote Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn